name: Linting Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install htmlhint and stylelint globally
    - name: Install htmlhint and stylelint globally
      run: |
        npm install -g htmlhint stylelint

    # Run HTML linting
    - name: Lint HTML files
      run: |
        echo "Running HTML linting..."
        htmlhint "**/*.html" || exit 1

    # Run CSS linting
    - name: Lint CSS files
      run: |
        echo "Running CSS linting..."
        stylelint "**/*.css" || exit 1



