name: Linting Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install htmlhint and stylelint globally
    - name: Install dependencies globally
      run: |
        npm install -g htmlhint stylelint

    # Run HTML linting
    - name: Lint HTML files
      run: |
        htmlhint "**/*.html"

    # Run CSS linting
    - name: Lint CSS files
      run: |
        stylelint "**/*.css"


